modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (28 is current forge version)
athors="Smakrypsletaren"

[[mods]] #mandatory
modId="whaarghhammer" #mandatory
version="0.1" #mandatory
displayName="WhaarghHammer" #mandatory
description='''
descrition¨
'''

[[dependencies.examplemod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
